---
- hosts: workers
  become: yes
  vars_files:
  - env_variables
  tasks:
  - name: Copying token to worker nodes
    copy: src={{ token_file }} dest=join_token

  - name: Joining worker nodes with kubernetes master
    shell: |
     sudo kubeadm reset -f
     sudo cat join_token | tail -2 > out.sh
     sudo sh out.sh
